spring.application.name=gateway
server.port=8765

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Rutas hacia los microservicios (load-balanced via Eureka)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=profile-service
spring.cloud.gateway.routes[1].uri=lb://profile-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/profiles/**

spring.cloud.gateway.routes[2].id=inventory-service
spring.cloud.gateway.routes[2].uri=lb://inventory-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/skins/**

spring.cloud.gateway.routes[3].id=catalog-service
spring.cloud.gateway.routes[3].uri=lb://catalog-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/catalog/**

spring.cloud.gateway.routes[4].id=cart-service
spring.cloud.gateway.routes[4].uri=lb://cart-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/cart/**

spring.cloud.gateway.routes[5].id=MarketplaceService
spring.cloud.gateway.routes[5].uri=lb://MarketplaceService
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/marketplace/**

spring.cloud.gateway.routes[6].id=rating-service
spring.cloud.gateway.routes[6].uri=lb://rating-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/ratings/**

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG