version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_inventory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: skinsarmas
      MYSQL_USER: 4rpuc
      MYSQL_PASSWORD: counterstrike26
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
